#port
server.port=5050

#Service id
spring.application.name=CUSTOMER-SERVICE

#Location of Config Server
spring.config.import=optional:configserver:http://localhost:8888


spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=mohit.au001@gmail.com
spring.mail.password=swdz uuos nnyv nhhf
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true